#%RAML 1.0 NamedExample

  -
    employeeld: "1"
    FName: jagruti
    LName: patil
    city: pune
    state: MH
    pin: "42"
    
  -
    employeeld: "2"
    FName: shivani
    LName: patil
    city: pune
    state: MH
    pin: "42" 
    
  